Repository reflation/backend, pull requests merged in 2019-11, with the labels that each got.

#13 test(models): mocking database for unit test (#10)
  bin/demo.ts
  bin/www.ts
  package.json
  src/@types/dreamy.ts
  src/@types/models.ts
  src/@types/params.ts
  src/checkVaild.ts
  src/index.test.ts
  src/index.ts
  src/models/__mocks__/index.ts
  src/models/index.ts
  src/routes.ts
  src/utils/fetch.ts
  src/utils/str2int.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#28 refact(types): use Pascal Case for type alias and interface
  src/@types/dreamy.ts
  src/@types/env.ts
  src/@types/models.ts
  src/@types/params.ts
  src/auth.ts
  src/checkVaild.ts
  src/index.test.ts
  src/jwt.ts
  src/models/__mocks__/index.ts
  src/models/index.ts
  src/routes.ts
  src/utils/fetch.ts
  src/utils/str2int.ts
  tsconfig.json
Labels: refact, types

#29 refact: function act as one thing
  src/utils/fetch.ts
Labels: refact

#31 feat: subject parse
  src/@types/dreamy.ts
  src/@types/models.ts
  src/utils/fetch.ts
Labels: feat

#33 fix: subjects type
  src/@types/models.ts
  src/models/index.ts
  src/models/prisma/index.ts
  src/utils/fetch.ts
Labels: bug, types

#38 lint(commit): modify prop to header-case
  .commitlintrc.json
Labels: linter

#35 chore(type): remove unuseful promise annotation
  src/models/index.ts
Labels: types

#40 chore: clean code param type
  src/@types/params.ts
  src/utils/fetch.ts
Labels: types
